// Next Elements
import Head from "next/head";
import Image from "next/image";

// STYLES
import styles from "@/styles/pages/Home.module.css";

// Components
import Navbar from "@/components/Navbar";

export default function Home() {
	return (
		<>
			{/* Header */}
			<Head>
				<title>Kyle Hu</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* Main Content */}
			<div className={styles.mainSection}>
				{/* Introduction Section */}
				<div className={styles.intro}>
					<div className={styles.introTitle}>Hello! My name is Kyle.</div>
					<div className={styles.introDesc}>
						I am an undergraduate student studying Computer Science at
						University of California Irvine. I enjoy web development and
						a fan of NextJS, TypeScript, and Supabase.
					</div>
				</div>
				
				
			</div>
		</>
	);
}
