// Next Elements
import Head from "next/head";
import Image from "next/image";

// Styles
import styles from "@/styles/pages/Home.module.css";

// Components
import PContainer from "@/components/ProjectContainer";

// Supabase functions
import { fetchProjectInfo } from "@/supabase/supabase";

// React
import { useEffect, useState } from "react";

interface indexProps{
	data: {
		desc: string;
		id: number;
		title: string;
	}[];
}

export default function Home(props:indexProps) {

	// const[projectInfo, setPInfo] = useState([{desc:"", id:-1, title:""}])

	// useEffect(() => {
	// 	const fetchProjectData = async () => {
	// 		const data = await fetchProjectInfo()
	// 		if(data){
	// 			setPInfo(data);
	// 		}
	// 	}

	// 	fetchProjectData();
	// }, [])

	console.log(props.data)

	return (
		<>
			{/* Header */}
			<Head>
				<title>Kyle Hu</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* Main Content */}
			<div className={styles.mainSection}>
				{/* Introduction Section */}
				<div className={styles.intro}>
					<div className={styles.introTitle}>Hello! My name is Kyle.</div>
					<div className={styles.introDesc}>
						I am an undergraduate student studying Computer Science at
						University of California Irvine. I enjoy web development and
						a fan of NextJS, TypeScript, and Supabase.
					</div>
				</div>
				
				{/* Project Section */}
				<div className={styles.projects}>
					<div className={styles.projTitle}>My Work</div>
					{/* Loop through the projects and display them in containers */}
					{props.data.map((project) => (
						<PContainer key={project.title} title={project.title} desc={project.desc} />
					))}
				</div>

			</div>
		</>
	);
}


export async function getServerSideProps() {
	// Fetch data from external API
	const data = await fetchProjectInfo()
   
	if(data){
		// Pass data to the page via props
		return { props: { data } }
	}
  }